name: Acquire Unity activation file

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Unity Hub repository
      run: |
        sudo apt-get install -y gnupg
        sudo mkdir -p /etc/apt/keyrings
        curl -sS https://packages.unity.com/unityhub.gpg | sudo gpg --dearmor -o /etc/apt/keyrings/unityhub.gpg
        echo "deb [signed-by=/etc/apt/keyrings/unityhub.gpg] https://hub-dist.unity3d.com/artifactory/hub-debian-prod-local stable main" | sudo tee /etc/apt/sources.list.d/unityhub.list > /dev/null
        sudo apt update

    - name: Install Unity Hub
      run: sudo apt install -y unityhub

    - name: Install Unity Editor
      run: |
        unityhub -- --headless install-path --set /opt/unity
        unityhub -- --headless install 2021.1.1f1

    - name: Create activation file
      run: |
        xvfb-run --auto-servernum --server-args='-screen 0 640x480x24' \
        /opt/unity/Editor/Unity \
        -batchmode \
        -nographics \
        -logFile /dev/stdout \
        -createManualActivationFile \
        -quit
