name: Acquire Unity activation file
on: workflow_dispatch

jobs:
  activation:
    name: Request manual activation file 🔑
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Request activation file job
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb gnupg
          
          # Install Unity Hub using the updated repository setup
          sudo mkdir -p /etc/apt/keyrings
          curl -sS https://packages.unity.com/unityhub.gpg | sudo gpg --dearmor -o /etc/apt/keyrings/unityhub.gpg
          echo "deb https://hub-dist.unity3d.com/artifactory/hub-debian-prod-local stable main" | sudo tee /etc/apt/sources.list.d/unityhub.list > /dev/null
          sudo apt update
          sudo apt install -y unityhub
          
          # Install Unity Editor
          unityhub -- --headless install-path --set /opt/unity
          unityhub -- --headless install 6000.0.34f1
          
          # Create activation file
          xvfb-run --auto-servernum --server-args='-screen 0 640x480x24' \
            /opt/unity/Editor/Unity \
            -batchmode \
            -nographics \
            -logFile /dev/stdout \
            -createManualActivationFile \
            -quit
          
      - name: Upload activation file
        uses: actions/upload-artifact@v4
        with:
          name: Unity_v6000.0.34f1.alf
          path: Unity_v6000.0.34f1.alf
          retention-days: 1

      - name: Next steps
        run: |
          echo "Manual activation file has been created and uploaded as an artifact."
          echo "Please follow these steps:"
          echo "1. Download the Unity_v6000.0.34f1.alf file from the artifacts"
          echo "2. Visit https://license.unity3d.com/manual"
          echo "3. Upload the .alf file"
          echo "4. Download the Unity_v6000.0.34f1.ulf file"
          echo "5. Create a new repository secret named UNITY_LICENSE"
          echo "6. Copy the entire contents of the .ulf file into the secret value"
