name: Unity Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build Unity Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Build project
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        run: |
          echo "Building Unity project..."
          echo "License found: ${{ secrets.UNITY_LICENSE != '' }}"
          
          # Add actual build steps once license is set up
          if [ -d "Assets" ]; then
            echo "✓ Assets directory found"
          else
            echo "✗ Assets directory not found"
            exit 1
          fi 